#!/bin/sh

EXTRA_HWDEF="test-extra.hwdef"
BOARD=MatekF405
# BOARD=revo-mini

cat >"$EXTRA_HWDEF" <<EOF
define GPS_BACKEND_DEFAULT_ENABLED 0
define GPS_BACKEND_UBLOX_ENABLED 1

undef HAL_PROBE_EXTERNAL_I2C_BAROS
define HAL_PROBE_EXTERNAL_I2C_BAROS 0

#undef AP_BARO_BMP085_ENABLED
#define AP_BARO_BMP085_ENABLED 0
#undef AP_BARO_BMP280_ENABLED
#define AP_BARO_BMP280_ENABLED 1

undef AP_BARO_MS56XX_ENABLED
define AP_BARO_MS6XX_ENABLED 0

undef AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED
define AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED 0
define AP_RCPROTOCOL_SBUS_ENABLED 1

define GPS_MAX_RECEIVERS 1

define HAL_BUTTON_ENABLED 0

define AP_RPM_ENABLED 0
define AP_ICENGINE_ENABLED 0

BOOTLOADER_EMBED 0

define AP_ADVANCEDFAILSAFE_ENABLED 0

define HAL_MAVLINK_INTERVALS_FROM_FILES_ENABLED 0

define HAL_SUPPORT_RCOUT_SERIAL 0

undef HAL_HOTT_TELEM_ENABLED
define HAL_HOTT_TELEM_ENABLED 0

undef HAL_SPEKTRUM_TELEM_ENABLED
define HAL_SPEKTRUM_TELEM_ENABLED 0

undef HAL_NAVEKF3_AVAILABLE 0
undef HAL_NAVEKF2_AVAILABLE 0
define HAL_NAVEKF3_AVAILABLE 0
define HAL_NAVEKF2_AVAILABLE 0





define WPNAV 0
define MORETHANQUAD 0

define AC_AVOID_ENABLED 0
define AC_FENCE 0
define AC_RALLY DISABLED
define AP_TERRAIN_AVAILABLE 0
define AC_TERRAIN DISABLED
define ADSB_ENABLED DISABLED
define AUTOTUNE_ENABLED DISABLED
define CAMERA DISABLED
define FRSKY_TELEM_ENABLED DISABLED
define MODE_AUTO_ENABLED DISABLED
define MODE_BRAKE_ENABLED DISABLED
define MODE_CIRCLE_ENABLED DISABLED
define MODE_DRIFT_ENABLED DISABLED
define MODE_FOLLOW_ENABLED DISABLED
define MODE_GUIDED_ENABLED DISABLED
define MODE_GUIDED_NOGPS_ENABLED DISABLED
define MODE_LOITER_ENABLED DISABLED
define MODE_POSHOLD_ENABLED DISABLED
define MODE_RTL_ENABLED DISABLED
define MODE_SMARTRTL_ENABLED DISABLED
define MODE_SPORT_ENABLED DISABLED
define MODE_SYSTEMID_ENABLED DISABLED
define MODE_THROW_ENABLED    DISABLED
define MODE_ZIGZAG_ENABLED   DISABLED
define MODE_ACRO_ENABLED DISABLED
define MODE_FLIP_ENABLED DISABLED
define LANDING_GEAR_ENABLED  DISABLED
define MOUNT DISABLED
define NAV_GUIDED DISABLED
define PARACHUTE DISABLED
undef PRECISION_LANDING
define PRECISION_LANDING DISABLED
define PROXIMITY_ENABLED DISABLED
define RANGEFINDER_ENABLED DISABLED
define SOLO_SUPPORT_ENABLED DISABLED
define SPRAYER DISABLED
define VISUAL_ODOMETRY_ENABLED DISABLED
define WINCH_ENABLED DISABLED
undef TOY_MODE_ENABLED
define TOY_MODE_ENABLED DISABLED
define OPTFLOW DISABLED
define GENERATOR_ENABLED 0
define AC_OAPATHPLANNER_ENABLED 0
define BUTTON_ENABLED DISABLED
define CAMERA DISABLED
define LOGGING_ENABLED DISABLED
define STATS_ENABLED DISABLED
undef OSD_ENABLED
define OSD_ENABLED 0
define OSD_PARAM_ENABLED 0 #apparently won't compile OSD excluded without this one out too
define HAL_BARO_WIND_COMP_ENABLED 0
define GRIPPER_ENABLED 0
define AP_PARAM_MAX_EMBEDDED_PARAM 1024
define HAL_WITH_DSP FALSE
define HAL_BATTMON_SMBUS_ENABLE 0
define HAL_BATTMON_FUEL_ENABLE 0

define HAL_LOGGING_ENABLED 0
define HAL_LOGGING_MAVLINK_ENABLED 0
define HAL_MISSION_ENABLED 0
define HAL_RALLY_ENABLED 0
# undef HAVE_FILESYSTEM_SUPPORT
# define HAVE_FILESYSTEM_SUPPORT 0 #seemed to .increase. build size by 8 bytes??
#define HAL_GCS_ENABLED 0

define HAL_MINIMISE_FEATURES ENABLED

# remove features:
define COMPASSMOT_ENABLED DISABLED
define PREARM_PID_CHECKS_ENABLED DISABLED


EOF

# ./Tools/autotest/test_build_options.py \
#     --no-run-with-defaults \
#     --no-disable-none \
#     --no-disable-in-turn \
#     --board="$BOARD" \
#     --extra-hwdef="$EXTRA_HWDEF"

./waf configure --board "$BOARD" --extra-hwdef="$EXTRA_HWDEF"
./waf copter