#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AC_AttitudeControl',
            'AC_InputManager',
            'AC_WPNav',
            'AP_InertialNav',
            'AP_RCMapper',
            'AP_Avoidance',
            'AP_Arming',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AP_OSD',
            'AP_KDECAN',
            'AP_Beacon',
        ],
    )

    bld.ap_program(
        program_name='ardublimp',
        program_groups=['bin', 'blimp'],
        use=vehicle + '_libs',
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME'],
        )

    # bld.ap_program(
    #     program_name='ardublimp-heli',
    #     program_groups=['bin', 'bheli'],
    #     use=vehicle + '_libs',
    #     defines=['FRAME_CONFIG=HELI_FRAME'],
    #     )
